version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: iss
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5000:5432"

  iss_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres